name: Deploy

on:
  workflow_dispatch:
      inputs:
        tag:
          description: 'Tag'
          required: true
          default: 'manual release'
          type: string
  push:
    tags:
      - "v**"

permissions:
  packages: write
  contents: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}

      - name: Yarn Install
        run: |
          corepack enable
          yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Create a Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          title: ${{ github.ref_name }}
          files: ./dist
          prerelease: false
          tag: ${{ inputs.tag || github.ref_name }}
