name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v**'

permissions:
  packages: write
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}

      - name: Yarn Install
        run: |
          corepack enable
          yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          workdir: ./dist
      